name: "Pull Request Manager"
on:
  schedule:
    - cron: '0 * * * *'

jobs:
  stale:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Process stale PRs
        uses: Sonia-corporation/stale@2.5.0
        with:
          issue-processing: false
          pull-request-days-before-stale: 14
          pull-request-days-before-close: 180
          pull-request-ignore-draft: true
          pull-request-ignore-all-milestones: true
          pull-request-stale-label: 'stale'
